# Page settings
baseurl = "localhost:1313" # metzgerforclerkandrecorder.com 
title = "Greg Metzger for Clerk and Recorder"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Greg Metzger"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Greg Metzger for Gallatin County Clerk and Recorder"
    subtitle = 'Greg Metzger, as Clerk and Recorder ensuring the accuracy of recorded Records, and the integrity, timeliness, and correctness of election results. Two of Montanan’s ultimate right to expect from their County government.
'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "I will bring my community experiences and leadership skills to the Clerk and Recorders office to not only continue the established excellence of todays office, but to adopt our systems to the continued growth of our population and voter base."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Community Involvement"
    description = "Getting to know your community includes being involved in it"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    
 

  # Services section
  [params.services]
    enable = true
    title = "Resume"
    description = "Professional Experience"

    [[params.services.item]]
      title = "Bozeman Fiber"
      description = "General Manager, Present- Start up operation to bring high speed broadband to help our county grow and prosper"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Ressler Motors"
      description = "Car sales 2016 -2017"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Montana Opticom"
      description = "Sales and Marketing Manager, 2015-2016 – market and sell high speed internet and broadband in the county."
      icon = "icon-video2"

      [[params.services.item]]
      title = "KBZK"
      description = "Sales and Marketing Manager for Gallatin and Silverbow counties, 2011 – 2014. Trained and lead award winning sales team"      
      icon = "icon-monitor"

      
      [[params.services.item]]
      title = "Aquilavision, PLC. COO, 2011"
      description = "Start –up data communications company"      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "CVR, Inc. dba Montana Furniture"
      description = "President, 1996 -2010 Pesident/Owner, developed manufacturing from $1.15 to over $5 million. Opened new markets with 6 new stores and more than 480 dealers in 23 states."      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "Sealed Air Corporation"
      description = "VP and General Manager, 1995 –Trigon Products division, manufacturing and sales of Banking and Air courier envelopes"      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "Trigon Packaging, CEO and President"
      description = "1987 -1994- Manufacturing, R & D, Sales and distribution of envelopes. Started as assistant production manager and ended up as President and CEO of International envelop company at the time of purchase by Sealed Air."      
      icon = "icon-monitor"
      
      [[params.services.item]]
      title = "Boeing Commercial Airplane Company "
      description = "Composites research technician and Project Manager, 1985-1987, Industrial Engineer 757 Line, 1985 -1986"      
      icon = "icon-monitor" 



  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contact Info"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Greg Metzger<br/>4 Park Plaza<br/>Bozeman Mt 59715"],
        ["icon-phone", "(406) 551-3265"],
        ["icon-envelope", "<a href='#'>metzgerforclerkandrecoder@gmail.com</a>"] 
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
