# Page settings
baseurl = "https://metzgerforclerkandrecorder.com" # localhost:1313
title = "Greg Metzger for Clerk and Recorder"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
   
  custom_css = ["/css/custom1.css"]

  # Meta
  author = ""
  fimage = "share.jpg"
  description = "Greg Metzger will bring community experiences and leadership skills to the Gallatin County Clerk and Recorder's Office."
  email = "metzgerforclerkandrecorder@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Greg Metzger"
    #home = "Home"
    about = "About/Issues"
    work = "Community"
    testimonials = "Testimonials"
    services = "Resume"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Greg Metzger for Gallatin County Clerk and Recorder"
    subtitle = 'Greg Metzger, as Clerk and Recorder, ensuring the accuracy of recorded Records, and the integrity, timeliness, and correctness of election results—two of a Montanan’s ultimate rights to expect from their county government.
'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "I will bring my community experiences and leadership skills to the Clerk and Recorder's Office to not only continue the established excellence of todays office but to adopt our systems to the continued growth of our population and voter base."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Community"
    description = "Getting to know your community includes being involved in it"
    footertext = ''

 

    [[params.work.row]] 
      title = "Bozeman Rotary"
      subtitle = "Member"

    [[params.work.row]] 
      title = "Mountain Valley Boy Scout Council"
      subtitle = "Member"

    [[params.work.row]] 
      title = "Montana State Boy Scout Council"
      subtitle = "VP Finances"

         [[params.work.row]] 
      title = "Leadership Montana"
      subtitle = "Graduate"

    [[params.work.row]] 
      title = "Mountain West Bank"
      subtitle = "Community Board Member"

    [[params.work.row]] 
      title = "Central Valley Fire District"
      subtitle = "Director "

    [[params.work.row]] 
      title = "Gallatin Airport Board"
      subtitle = "Director "

    [[params.work.row]] 
      title = "MSU Jake Jabs College of Business and Entrepreneurship"
      subtitle = "Board of Advisors"

    [[params.work.row]] 
      title = "MSU School of Advisors"
      subtitle = "Chairman (1 year)"

    [[params.work.row]] 
      title = "Riverside Country Club"
      subtitle = "Board Member"

    [[params.work.row]] 
      title = "Riverside Country Club "
      subtitle = "Chairman (2 years)"

    [[params.work.row]] 
      title = "Gallatin County"
      subtitle = "Planning Board"

    [[params.work.row]] 
      title = " Bozeman Area Chamber of Commerce"
      subtitle = "Board of Directors (2 terms)"

    [[params.work.row]] 
      title = " Chamber"
      subtitle = "Chairman  (1 year)"

    [[params.work.row]] 
      title = "Bozeman Police Board Foundation"
      subtitle = "Board Member" 

    [[params.work.row]] 
      title = "Gallatin County Compensation Committee"
      subtitle = "Member" 


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Description"

    [[params.testimonials.item]]
      quote = "&ldquo;Description Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Description Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Description&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Description &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    
 

  # Services section
  [params.services]
    enable = true
    title = "Resume"
    description = "Professional Experience"

    [[params.services.item]]
      title = "Bozeman Fiber"
      description = "General Manager, Present, Start up operation to bring high speed broadband to Bozeman and help our county grow and prosper"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Ressler Motors"
      description = "Car sales, 2016-2017"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Montana Opticom"
      description = "Sales and Marketing Manager, 2015-2016, market and sell high speed internet and broadband in the county."
      icon = "icon-video2"

      [[params.services.item]]
      title = "KBZK"
      description = "Sales and Marketing Manager for Gallatin and Silverbow counties, 2011–2014, Trained and lead award winning sales team"      
      icon = "icon-monitor"

      
      [[params.services.item]]
      title = "Aquilavision, PLC. "
      description = "COO, 2011, Start–up data communications company"      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "CVR, Inc. dba Montana Furniture"
      description = "President, 1996-2010, Pesident/Owner, developed manufacturing from $1.15 to over $5 million. Opened new markets with 6 new stores and more than 480 dealers in 23 states."      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "Sealed Air Corporation"
      description = "VP and General Manager, 1995, Trigon Products division, manufacturing and sales of banking and air courier envelopes"      
      icon = "icon-monitor"

      [[params.services.item]]
      title = "Trigon Packaging"
      description = "CEO and President, 1987-1994, Manufacturing, R & D, Sales and distribution of envelopes. Started as assistant production manager and ended up as President and CEO of International envelop company at the time of purchase by Sealed Air."      
      icon = "icon-monitor"
      
      [[params.services.item]]
      title = "Boeing Commercial Airplane Company "
      description = "Project Manager and Industrial Engineer, 1985-1987, Composites research technician and Project Manager, 1985-1987; Industrial Engineer 757 Line, 1985-1986"      
      icon = "icon-monitor" 

      [[params.services.item]]
      title = "U.S. Navy "
      description = "Various, 1974-1981, Aerographers Mate 1st Class; Worked in Typhoon Warning Center (Guam) 1975-1977; Worked as Midwest Weather Training Officer and Flight Forecaster, Glenview Il, 1977-1979; Worked as a Flight Forecaster, Whidbey Island, WA 1979-1981"      
      icon = "icon-monitor" 


      

  [edu.services]
    enable = true
    title = "Resume"
    description = "Professional Experience"
       [[params.edu.item]]
      title = "MBA, Engineering and Technical Management; 1987 City University, Bellevue WA." 
       [[params.edu.item]]
      title = "BS, Industrial Technology; 1985 Western Washington University, Bellingham WA."  



  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Description"

    [[params.about.item]]
      qid = "1"
      name = "What are the roles and duties of Clerk and Recorder?" 
      description = "<ol><li>The county clerk of a county is also clerk of the county commissioners and ex officio recorder. A duty imposed by law upon the officer, whether as county clerk, clerk of the county commissioners, or recorder, must be performed by the county clerk, and any official act performed or certified by the county clerk is as valid and effectual as if performed and certified by the clerk of the county commissioners or the recorder.</li><li>The county clerk shall:<ol type='a'><li>take charge of and safely keep or dispose of according to law all books, papers, maps, and records that may be filed or deposited in the county clerk&rsquo;s office;</li><li>record all the proceedings of the board;</li><li>make full entries of all its resolutions and decisions on all questions concerning the raising of money for and the allowance of accounts against the county;</li><li>record the vote of each member on a question upon which there is a division or at the request of any member present;</li><li>sign all orders made and warrants issued by order of the board for the payment of money and certify the orders and warrants to the county treasurer;</li><li>record the reports of the county treasurer of the receipts and disbursements of the county;</li><li>preserve and file all accounts acted upon by the board;</li><li>preserve and file all petitions and applications for franchises and record the action of the board on the petitions and applications;</li><li>record all orders levying taxes;</li><li>designate upon each account allowed by the board the amount allowed and deliver to any person who may demand it a certified copy of any record or any account on file in the county clerk&rsquo;s office;</li><li>when a new township is organized or the boundaries of a township are altered, immediately make out and transmit to the secretary of state a certified statement of the names and boundaries of the township organized or altered;</li><li>keep other records and books and perform other duties that are prescribed by law or by rule or order of the board.</li></ol></li><li>An election administrator shall file, code, and cross-index all reports and statements filed as prescribed by the commissioner of political practices.</li><li>An election administrator shall make statements and other information filed under the provisions of Title 13, chapters 35, 36, and 37, available for public inspection and copying during the office hours determined by the governing body by resolution after a public hearing and make copying facilities available free of charge or at a charge not to exceed actual cost.</li></ol>"
      
    [[params.about.item]]
     qid = "2"
      name = "Why do you want this position?" 
      description = "I love being an American.  The essence of freedom is the ability to vote and select your own government.  Next would be the ownership of land or a home.<br/><br/>The Clerk and Recorder position is charged with running the elections and recording the transfer of land ownership, administering oaths of office and ensuring the orderly progression of government and life."  
    [[params.about.item]]
      qid = "3"
      name = "What qualifies you for this job?" 
      description = "I have been a manager for most of the last 35 years.  Serving in the US Navy, I was a manager (Aerographers Mate 1st Class) of a shift in the weather office and in charge of training.  After my undergraduate school (BS Industrial technology), I worked at Boeing as an Industrial Engineer, sequencing parts and the installation of those parts in 757’s.  I then moved to a composites research division and, while doing my own research, I also ran the budgets and schedules for the other engineers in my group.<br/><br/>During this period at Boeing, I started and completed my MBA.  This allowed me to move to Trigon Packaging, a New Zealand based company with a factory in Seattle.  I started as Assistant Planner and ended up as the President a year later.  About 18 months after that, I was given responsibility for plants in England and France.  We then added another plant in Cambridge England and built another U.S. plant in Atlanta.  This brought my responsibility to over 600 employees.<br/><br/>The company was sold on Dec 31, 1994.  I stayed with the new company, Sealed Air, through 1995 and then came to Montana in 1996.  We bought Montana Furniture and grew the factory and added six more stores also distributing and selling furniture in 23 states.  At our maximum, we had more than 140 employees in three states.  With the recession, we were forced to close our operation in 2010.<br/><br/>Since then, I have worked for KBZK as the Sales and Marketing Manager, Ressler Motors as a sales person and currently as the General Manager of Bozeman Fiber.<br/><br/>So, the short answer is I have a significant amount of experience in various management roles in a variety of industries and businesses.  My strengths are the creation of efficient and productive teams, molding technology into an integral part of business and being flexible and capable of changing as a situation, technology and/or business evolves. With these experiences comes extensive budgeting and planning abilities."  
    [[params.about.item]]
      qid = "4"
      name = "How long have you lived in Bozeman?" 
      description = "Since October 1996."  
    [[params.about.item]]
      qid = "5"
      name = "Have you ever worked in the Recorder or Elections Office?" 
      description = "I worked in the Elections Office in 2017 as a helper in the primary and general elections."  
    [[params.about.item]]
      qid = "6"
      name= "Have you been active in the Gallatin Valley? "
      description = "My family and I have been active in a variety of activities through the years. Please see the “Community” section below for some of the details on my activities."  
    [[params.about.item]]
      qid = "7"
      name = "Have you ever held a public office?" 
      description = "I was a Precinct Person for 3 terms. In addition, the director position of the Central Valley Fire district was an elected position, as is the Riverside Water and Sewer District. "  
  

  [params.issues]
  enable = true
  title = "Issues"
    description = "Description"
  
    [[params.issues.item]]
    list = "Match quality of security and accuracy with record voter growth." 
    [[params.issues.item]]
    list = "Ensure records are accurate and available to the public 24&sol;7." 
    [[params.issues.item]]
    list = "Pursue processes that make voter registration easy, but accurate." 
    [[params.issues.item]]
    list = "Apply “Best Practices” to our technology in all processes." 
    [[params.issues.item]]
    list = "Manage budget effectively ensuring we charge appropriately for services and that we provide value for those services." 
    [[params.issues.item]]
    list = "Use experience on Planning Board to ensure fairness and accuracy in the Planning and Zoning Commission." 
    
  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contact Info"
    description = "Description"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Greg Metzger<br/>4 Park Plaza<br/>Bozeman MT 59715"],
        ["icon-phone", "(406) 551-3265"],
        ["icon-envelope", "<a href='mail&#116;o&#58;&#109;&#37;65&#116;&#122;gerforcler&#107;an&#100;%7&#50;ec&#111;%72der%&#52;0gm%&#54;1il&#46;c%6Fm'>&#109;e&#116;zg&#101;&#114;&#102;o&#114;clerkand&#114;&#101;c&#111;&#114;der&#64;gma&#105;&#108;&#46;com</a>"] 
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Paid for by Metzger for Clerk and Recorder <br/><small>&copy; Elate Free HTML5. All Rights Reserved. | Created by <a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>  |  Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a></small>'
    